[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch]$Apply
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

if (-not (Test-Path (Join-Path $root 'Antigravity.sln'))) {
    throw "Safety guard failed: Antigravity.sln was not found in $root"
}

Write-Host 'ANTIGRAVITY REPOSITORY CLEANUP - BATCH 1' -ForegroundColor Cyan
Write-Host "Root: $root" -ForegroundColor DarkGray
Write-Host 'Scope: generated/build/cache/legacy diagnostic artifacts only.' -ForegroundColor DarkGray
Write-Host 'Protected: source WIP, IssueManager changes, TagArranger plans, fixtures, release archives.' -ForegroundColor DarkGray

$removedFiles = New-Object System.Collections.Generic.List[string]
$removedDirs  = New-Object System.Collections.Generic.List[string]

function Remove-ExplicitFile {
    param([Parameter(Mandatory = $true)][string]$RelativePath)

    $path = Join-Path $root $RelativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { return }

    if ($Apply) {
        Remove-Item -LiteralPath $path -Force
        $removedFiles.Add($RelativePath)
        Write-Host "[DELETE FILE] $RelativePath" -ForegroundColor Yellow
    } else {
        Write-Host "[WOULD DELETE FILE] $RelativePath" -ForegroundColor DarkYellow
    }
}

function Remove-ExplicitDirectory {
    param([Parameter(Mandatory = $true)][string]$RelativePath)

    $path = Join-Path $root $RelativePath
    if (-not (Test-Path -LiteralPath $path -PathType Container)) { return }

    if ($Apply) {
        Remove-Item -LiteralPath $path -Recurse -Force
        $removedDirs.Add($RelativePath)
        Write-Host "[DELETE DIR ] $RelativePath" -ForegroundColor Yellow
    } else {
        Write-Host "[WOULD DELETE DIR ] $RelativePath" -ForegroundColor DarkYellow
    }
}

# Top-level local/generated directories. Release/history directories such as
# _Installer, _packages and _addin_manager are intentionally NOT part of Batch 1.
@(
    '.vs',
    '.pytest_cache',
    '.tmp',
    'source-code',
    '.agent\reports',
    '.agent\state',
    '.agent\context',
    '.agents\context',
    '.vscode',
    'Workflow'
) | ForEach-Object { Remove-ExplicitDirectory $_ }

# Generated directories below source/test/runtime roots only. Never traverse .git.
$scanRoots = @('src', 'tests', '.agents')
$generatedDirNames = @('bin', 'obj', 'TestResults', '__pycache__', '.vs')
foreach ($scanRoot in $scanRoots) {
    $absoluteScanRoot = Join-Path $root $scanRoot
    if (-not (Test-Path -LiteralPath $absoluteScanRoot -PathType Container)) { continue }

    $generatedDirs = Get-ChildItem -LiteralPath $absoluteScanRoot -Directory -Recurse -Force -ErrorAction SilentlyContinue |
        Where-Object { $generatedDirNames -contains $_.Name } |
        Sort-Object { $_.FullName.Length } -Descending

    foreach ($dir in $generatedDirs) {
        $relative = $dir.FullName.Substring($root.Length).TrimStart('\')
        if ($Apply) {
            Remove-Item -LiteralPath $dir.FullName -Recurse -Force
            $removedDirs.Add($relative)
            Write-Host "[DELETE DIR ] $relative" -ForegroundColor Yellow
        } else {
            Write-Host "[WOULD DELETE DIR ] $relative" -ForegroundColor DarkYellow
        }
    }
}

# Root/local diagnostics and compiled one-off artifacts confirmed by forensic review.
@(
    'debug_dump.json',
    'debug_files.txt',
    'build_errors.log',
    'scratch_pytest_output.txt',
    'test_output.txt',
    'Dang',
    'prompt.txt',
    'test_serialize.exe',
    'TestParse.exe',
    'TestZip.exe',
    'Antigravity.Core.dll',
    'Antigravity.IssueManager.dll',
    '.ai-bridge\codexpro-self-test.md',
    '.ai-bridge\pro-context.md'
) | ForEach-Object { Remove-ExplicitFile $_ }

# WPF temporary project files are generated by the XAML build pipeline.
$srcRoot = Join-Path $root 'src'
if (Test-Path -LiteralPath $srcRoot -PathType Container) {
    Get-ChildItem -LiteralPath $srcRoot -Filter '*_wpftmp.csproj' -File -Recurse -Force -ErrorAction SilentlyContinue |
        ForEach-Object {
            $relative = $_.FullName.Substring($root.Length).TrimStart('\')
            if ($Apply) {
                Remove-Item -LiteralPath $_.FullName -Force
                $removedFiles.Add($relative)
                Write-Host "[DELETE FILE] $relative" -ForegroundColor Yellow
            } else {
                Write-Host "[WOULD DELETE FILE] $relative" -ForegroundColor DarkYellow
            }
        }
}

# Preserve the repository's current .gitignore. Cleanup must never replace the
# whole file with an embedded historical template; append only missing generated/
# transient-state rules required by this maintenance script.
$gitignorePath = Join-Path $root '.gitignore'
$requiredGitignoreRules = @(
    '.pytest_cache/',
    '**/__pycache__/',
    '*.pyc',
    '*.pyo',
    '.agent/context/',
    '.agent/state/',
    '.agent/reports/',
    '.agents/context/',
    '.agents/factory/',
    '.ai-bridge/',
    '**/smoke-tests/results/*',
    '!**/smoke-tests/results/.gitkeep'
)
$currentGitignore = if (Test-Path -LiteralPath $gitignorePath -PathType Leaf) {
    [System.IO.File]::ReadAllText($gitignorePath)
} else {
    ''
}
$existingGitignoreLines = @($currentGitignore -split "`r?`n")
$missingGitignoreRules = @($requiredGitignoreRules | Where-Object { $existingGitignoreLines -notcontains $_ })

if ($Apply) {
    if ($missingGitignoreRules.Count -gt 0) {
        $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
        $prefix = if ([string]::IsNullOrWhiteSpace($currentGitignore)) { '' } elseif ($currentGitignore.EndsWith("`n")) { "`n" } else { "`r`n`r`n" }
        $appendText = $prefix + "# Added by scripts/maintenance/CleanProject.ps1`r`n" + (($missingGitignoreRules -join "`r`n") + "`r`n")
        [System.IO.File]::AppendAllText($gitignorePath, $appendText, $utf8NoBom)
        Write-Host "[APPEND] .gitignore missing rules: $($missingGitignoreRules.Count)" -ForegroundColor Green
    } else {
        Write-Host '[KEEP] .gitignore already contains required cleanup rules.' -ForegroundColor Green
    }
} elseif ($missingGitignoreRules.Count -gt 0) {
    Write-Host "[WOULD APPEND] .gitignore missing rules: $($missingGitignoreRules.Count)" -ForegroundColor DarkGreen
} else {
    Write-Host '[KEEP] .gitignore already contains required cleanup rules.' -ForegroundColor DarkGreen
}

Write-Host ''
if ($Apply) {
    Write-Host "Batch 1 complete. Removed directories: $($removedDirs.Count); files: $($removedFiles.Count)." -ForegroundColor Green
    Write-Host 'No release/archive directories were touched.' -ForegroundColor Green
    Write-Host 'Review git status before staging or committing.' -ForegroundColor Cyan
} else {
    Write-Host 'Preview only. Re-run with -Apply to perform the cleanup.' -ForegroundColor Cyan
}
