param()

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$src = Join-Path $root 'src'
$errors = New-Object System.Collections.Generic.List[string]
$warnings = New-Object System.Collections.Generic.List[string]

function Add-Error([string]$Message) { $errors.Add($Message) }
function Require-Path([string]$RelativePath, [string]$Context) {
    if (-not (Test-Path -LiteralPath (Join-Path $root $RelativePath))) {
        Add-Error ("${Context}: missing $RelativePath")
    }
}
function Read-JsonSafe([string]$Path, [string]$Label) {
    if (-not (Test-Path -LiteralPath $Path)) { Add-Error ("missing $Label"); return $null }
    try { return Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json }
    catch { Add-Error ("invalid JSON $Label - $($_.Exception.Message)"); return $null }
}

$requiredRepoPaths = @(
    'docs\projects\PROJECTS.md',
    'docs\architecture\REPOSITORY_STRUCTURE.md',
    'docs\architecture\MODULE_PLACEMENT.md',
    'docs\plans',
    'docs\reports',
    'docs\standards',
    'docs\templates',
    'scripts\architecture\Generate-ArchitectureGraph.ps1',
    'scripts\architecture\understand_config.json',
    'packaging'
)
foreach ($path in $requiredRepoPaths) { Require-Path $path 'repository' }

foreach ($forbidden in @('docs\superpowers','plans')) {
    if (Test-Path -LiteralPath (Join-Path $root $forbidden)) {
        Add-Error ("obsolete repository path still exists: $forbidden")
    }
}

$registryText = if (Test-Path -LiteralPath (Join-Path $root 'docs\projects\PROJECTS.md')) { Get-Content -LiteralPath (Join-Path $root 'docs\projects\PROJECTS.md') -Raw } else { '' }
$projectCount = 0
$deferredCount = 0

$projectDirs = Get-ChildItem -LiteralPath $src -Directory | Where-Object { $_.Name -like 'Antigravity.*' } | Sort-Object Name
foreach ($dir in $projectDirs) {
    $projectCount++
    $hasCsproj = @(Get-ChildItem -LiteralPath $dir.FullName -File -Filter '*.csproj' | Where-Object { $_.DirectoryName -eq $dir.FullName }).Count -gt 0
    if (-not $hasCsproj) { $deferredCount++ }

    foreach ($relative in @(
        'PROJECT.md',
        'docs\plans\ROADMAP.md',
        'docs\reports\2026-08-23-artifact-structure-migration.md'
    )) {
        $path = Join-Path $dir.FullName $relative
        if (-not (Test-Path -LiteralPath $path)) { Add-Error ("$($dir.Name): missing $relative") }
    }

    if ($registryText -notmatch [regex]::Escape($dir.Name)) {
        Add-Error ("$($dir.Name): missing from docs/projects/PROJECTS.md")
    }

    if ($hasCsproj) {
        foreach ($relative in @(
            'docs\plans',
            'docs\design',
            'docs\acceptance',
            'docs\reports',
            'smoke-tests\README.md',
            'smoke-tests\smoke-manifest.json',
            'smoke-tests\baseline\last-known-good.json',
            'smoke-tests\baseline\expected-behavior.md',
            'smoke-tests\scripts',
            'smoke-tests\fixtures',
            'smoke-tests\results\.gitkeep'
        )) {
            if (-not (Test-Path -LiteralPath (Join-Path $dir.FullName $relative))) {
                Add-Error ("$($dir.Name): missing $relative")
            }
        }

        $manifest = Read-JsonSafe (Join-Path $dir.FullName 'smoke-tests\smoke-manifest.json') ($dir.Name + '/smoke-manifest.json')
        $lkg = Read-JsonSafe (Join-Path $dir.FullName 'smoke-tests\baseline\last-known-good.json') ($dir.Name + '/last-known-good.json')
        if ($manifest) {
            if ($manifest.project -ne $dir.Name) { Add-Error ("$($dir.Name): smoke manifest project mismatch '$($manifest.project)'") }
            if (-not $manifest.smokeChecks -or @($manifest.smokeChecks).Count -eq 0) { Add-Error ("$($dir.Name): smokeChecks missing/empty") }
        }
        if ($lkg -and $lkg.smokeStatus -eq 'PASS') {
            Add-Error ("$($dir.Name): unverified PASS is forbidden in rollout last-known-good")
        }
    }
}

$activeGovernanceFiles = @(
    '.agents\AGENTS.md',
    '.agents\policies\repository-structure.md',
    '.agents\skills\addin-artifact-governance\SKILL.md',
    '.agents\skills\1-spec\SKILL.md',
    '.agents\skills\2-plan\SKILL.md',
    '.agents\skills\3-code\SKILL.md',
    '.agents\skills\4-ship\SKILL.md',
    '.agents\skills\dual-agent\SKILL.md',
    '.agents\skills\dual-agent-pipeline\SKILL.md'
)
foreach ($relative in $activeGovernanceFiles) {
    $path = Join-Path $root $relative
    if (-not (Test-Path -LiteralPath $path)) { Add-Error ("active governance missing: $relative"); continue }
    $text = Get-Content -LiteralPath $path -Raw
    if ($text -match 'docs/superpowers/plans/') { Add-Error ("active governance has obsolete plan path: $relative") }
}

# Generated bytecode may be recreated locally by tests and is ignored by Git. What
# must not survive as durable review input is a historically tracked bytecode file
# that is still physically present. Deleted tracked files are allowed so cleanup can
# be reviewed before commit/push authorization.
$trackedFiles = @(& git -C $root ls-files 2>$null)
if ($LASTEXITCODE -ne 0) {
    Add-Error 'unable to inspect tracked files for generated Python artifacts'
} else {
    $trackedGeneratedPython = @($trackedFiles | Where-Object {
        $_ -like '*__pycache__/*' -or $_.EndsWith('.pyc') -or $_.EndsWith('.pyo')
    })
    foreach ($relative in $trackedGeneratedPython) {
        $absolute = Join-Path $root ($relative -replace '/', '\')
        if (Test-Path -LiteralPath $absolute -PathType Leaf) {
            Add-Error ("tracked generated Python artifact is still present: $relative")
        }
    }
}

# .ai-bridge is transient runtime/handoff state. Repository governance must remain
# valid in a clean clone where the directory does not exist.
$handoffPath = Join-Path $root '.ai-bridge\current-plan.md'
if (Test-Path -LiteralPath $handoffPath) {
    $warnings.Add('.ai-bridge/current-plan.md is present as transient runtime state; it is not a canonical governance dependency.')
}

$summaryPath = Join-Path $root 'docs\reports\2026-08-23-addin-artifact-governance-rollout.md'
if (-not (Test-Path -LiteralPath $summaryPath)) { Add-Error 'missing Phase 5 cross-solution rollout summary' }

Write-Host ("Projects indexed      : {0}" -f $projectCount)
Write-Host ("Deferred no-csproj    : {0}" -f $deferredCount)
Write-Host ("Errors                : {0}" -f $errors.Count)
foreach ($error in $errors) { Write-Host ("[ERROR] {0}" -f $error) }
foreach ($warning in $warnings) { Write-Host ("[WARN ] {0}" -f $warning) }

if ($errors.Count -gt 0) { exit 1 }
Write-Host 'PHASE6_REPOSITORY_GOVERNANCE_VALIDATION_PASS'
